name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-a12-kernel:
    uses: ./.github/workflows/build-kernel-a12.yml
    secrets: inherit
  build-a13-kernel:
    uses: ./.github/workflows/build-kernel-a13.yml
    secrets: inherit
  build-a14-kernel:
    uses: ./.github/workflows/build-kernel-a14.yml
    secrets: inherit
  release:
    needs:
      - build-a12-kernel
      - build-a13-kernel
      - build-a14-kernel
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Zip AnyKernel3
        run: |
          for dir in AnyKernel3-*; do
            if [ -d "$dir" ]; then
              echo "----- Zip $dir -----"
              (cd $dir && zip -r9 "$dir".zip ./* -x .git .gitignore ./*.zip && mv *.zip ..)
            fi
          done

      - name: Display structure of downloaded files
        run: ls -R
        
      - name: set env
        run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
    
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NOW }}
          files: |
            AnyKernel3-*.zip
            boot-images-*/Image-*/*.img.gz
